<?php

use Illuminate\Database\Seeder;

class BankTableSeeder extends Seeder
{

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // DB::table('banks')->insert([
        //     ['name' => 'Banco ABN AMRO Real S.A.', 'code' => '356'],
        //     ['name' => 'Banco Alfa S.A.', 'code' => '25'],
        //     ['name' => 'Banco Alvorada S.A.', 'code' => '641'],
        //     ['name' => 'Banco Banerj S.A.', 'code' => '29'],
        //     ['name' => 'Banco Banestado S.A.', 'code' => '38'],
        //     ['name' => 'Banco Barclays S.A.', 'code' => '740'],
        //     ['name' => 'Banco BBM S.A.', 'code' => '107'],
        //     ['name' => 'Banco Beg S.A.', 'code' => '31'],
        //     ['name' => 'Banco Bem S.A.', 'code' => '36'],
        //     ['name' => 'Banco BM&F de Serviços de Liquidação e Custódia S.A', 'code' => '96'],
        //     ['name' => 'Banco BMC S.A.', 'code' => '394'],
        //     ['name' => 'Banco BMG S.A.', 'code' => '318'],
        //     ['name' => 'Banco BNP Paribas Brasil S.A.', 'code' => '752'],
        //     ['name' => 'Banco Boavista Interatlântico S.A.', 'code' => '248'],
        //     ['name' => 'Banco Bradesco S.A.', 'code' => '237'],
        //     ['name' => 'Banco Brascan S.A.', 'code' => '225'],
        //     ['name' => 'Banco Cacique S.A.', 'code' => '263'],
        //     ['name' => 'Banco Calyon Brasil S.A.', 'code' => '222'],
        //     ['name' => 'Banco Cargill S.A.', 'code' => '40'],
        //     ['name' => 'Banco Citibank S.A.', 'code' => '745'],
        //     ['name' => 'Banco Comercial e de Investimento Sudameris S.A.', 'code' => '215'],
        //     ['name' => 'Banco Cooperativo do Brasil S.A. – BANCOOB', 'code' => '756'],
        //     ['name' => 'Banco Cooperativo Sicredi S.A. – BANSICREDI', 'code' => '748'],
        //     ['name' => 'Banco Credit Suisse (Brasil) S.A.', 'code' => '505'],
        //     ['name' => 'Banco Cruzeiro do Sul S.A.', 'code' => '229'],
        //     ['name' => 'Banco da Amazônia S.A.', 'code' => '3'],
        //     ['name' => 'Banco Daycoval S.A.', 'code' => '707'],
        //     ['name' => 'Banco de Pernambuco S.A. – BANDEPE', 'code' => '24'],
        //     ['name' => 'Banco de Tokyo-Mitsubishi UFJ Brasil S.A.', 'code' => '456'],
        //     ['name' => 'Banco Dibens S.A.', 'code' => '214'],
        //     ['name' => 'Banco do Brasil S.A.', 'code' => '1'],
        //     ['name' => 'Banco do Estado de Santa Catarina S.A.', 'code' => '27'],
        //     ['name' => 'Banco do Estado de Sergipe S.A.', 'code' => '47'],
        //     ['name' => 'Banco do Estado do Pará S.A.', 'code' => '37'],
        //     ['name' => 'Banco do Estado do Rio Grande do Sul S.A.', 'code' => '41'],
        //     ['name' => 'Banco do Nordeste do Brasil S.A.', 'code' => '4'],
        //     ['name' => 'Banco Fator S.A.', 'code' => '265'],
        //     ['name' => 'Banco Fibra S.A.', 'code' => '224'],
        //     ['name' => 'Banco Finasa S.A.', 'code' => '175'],
        //     ['name' => 'Banco Fininvest S.A.', 'code' => '252'],
        //     ['name' => 'Banco GE Capital S.A.', 'code' => '233'],
        //     ['name' => 'Banco Gerdau S.A.', 'code' => '734'],
        //     ['name' => 'Banco Guanabara S.A.', 'code' => '612'],
        //     ['name' => 'Banco Ibi S.A. Banco Múltiplo', 'code' => '63'],
        //     ['name' => 'Banco Industrial do Brasil S.A.', 'code' => '604'],
        //     ['name' => 'Banco Industrial e Comercial S.A.', 'code' => '320'],
        //     ['name' => 'Banco Indusval S.A.', 'code' => '653'],
        //     ['name' => 'Banco Intercap S.A.', 'code' => '630'],
        //     ['name' => 'Banco Investcred Unibanco S.A.', 'code' => '249'],
        //     ['name' => 'Banco Itaú BBA S.A.', 'code' => '184'],
        //     ['name' => 'Banco Itaú Holding Financeira S.A.', 'code' => '652'],
        //     ['name' => 'Banco Itaú S.A.', 'code' => '341'],
        //     ['name' => 'Banco ItaúBank S.A', 'code' => '479'],
        //     ['name' => 'Banco J. P. Morgan S.A.', 'code' => '376'],
        //     ['name' => 'Banco J. Safra S.A.', 'code' => '74'],
        //     ['name' => 'Banco Luso Brasileiro S.A.', 'code' => '600'],
        //     ['name' => 'Banco Mercantil de São Paulo S.A.', 'code' => '392'],
        //     ['name' => 'Banco Mercantil do Brasil S.A.', 'code' => '389'],
        //     ['name' => 'Banco Merrill Lynch de Investimentos S.A.', 'code' => '755'],
        //     ['name' => 'Banco Nossa Caixa S.A.', 'code' => '151'],
        //     ['name' => 'Banco Opportunity S.A.', 'code' => '45'],
        //     ['name' => 'Banco Panamericano S.A.', 'code' => '623'],
        //     ['name' => 'Banco Paulista S.A.', 'code' => '611'],
        //     ['name' => 'Banco Pine S.A.', 'code' => '643'],
        //     ['name' => 'Banco Prosper S.A.', 'code' => '638'],
        //     ['name' => 'Banco Rabobank International Brasil S.A.', 'code' => '747'],
        //     ['name' => 'Banco Rendimento S.A.', 'code' => '633'],
        //     ['name' => 'Banco Rural Mais S.A.', 'code' => '72'],
        //     ['name' => 'Banco Rural S.A.', 'code' => '453'],
        //     ['name' => 'Banco Safra S.A.', 'code' => '422'],
        //     ['name' => 'Banco Santander Banespa S.A.', 'code' => '8'],
        //     ['name' => 'Banco Schahin S.A.', 'code' => '250'],
        //     ['name' => 'Banco Simples S.A.', 'code' => '749'],
        //     ['name' => 'Banco Société Générale Brasil S.A.', 'code' => '366'],
        //     ['name' => 'Banco Sofisa S.A.', 'code' => '637'],
        //     ['name' => 'Banco Sudameris Brasil S.A.', 'code' => '347'],
        //     ['name' => 'Banco Sumitomo Mitsui Brasileiro S.A.', 'code' => '464'],
        //     ['name' => 'Banco Triângulo S.A.', 'code' => '634'],
        //     ['name' => 'Banco UBS Pactual S.A.', 'code' => '208'],
        //     ['name' => 'Banco UBS S.A.', 'code' => '247'],
        //     ['name' => 'Banco Único S.A.', 'code' => '116'],
        //     ['name' => 'Banco Votorantim S.A.', 'code' => '655'],
        //     ['name' => 'Banco VR S.A.', 'code' => '610'],
        //     ['name' => 'Banco WestLB do Brasil S.A.', 'code' => '370'],
        //     ['name' => 'BANESTES S.A. Banco do Estado do Espírito Santo', 'code' => '21'],
        //     ['name' => 'Banif-Banco Internacional do Funchal (Brasil)S.A.', 'code' => '719'],
        //     ['name' => 'Bankpar Banco Multiplo S.A.', 'code' => '204'],
        //     ['name' => 'BB Banco Popular do Brasil S.A.', 'code' => '73'],
        //     ['name' => 'BPN Brasil Banco Mútiplo S.A.', 'code' => '69'],
        //     ['name' => 'BRB – Banco de Brasília S.A.', 'code' => '70'],
        //     ['name' => 'Caixa Econômica Federal', 'code' => '104'],
        //     ['name' => 'Citibank N.A.', 'code' => '477'],
        //     ['name' => 'Deutsche Bank S.A. – Banco Alemão', 'code' => '487'],
        //     ['name' => 'Dresdner Bank Brasil S.A. – Banco Múltiplo', 'code' => '751'],
        //     ['name' => 'Dresdner Bank Lateinamerika Aktiengesellschaft', 'code' => '210'],
        //     ['name' => 'Hipercard Banco Múltiplo S.A.', 'code' => '62'],
        //     ['name' => 'HSBC Bank Brasil S.A. – Banco Múltiplo', 'code' => '399'],
        //     ['name' => 'ING Bank N.V.', 'code' => '492'],
        //     ['name' => 'JPMorgan Chase Bank', 'code' => '488'],
        //     ['name' => 'Lemon Bank Banco Múltiplo S.A.', 'code' => '65'],
        //     ['name' => 'UNIBANCO – União de banks Brasileiros S.A.', 'code' => '409'],
        //     ['name' => 'Unicard Banco Múltiplo S.A.', 'code' => '230'],
        // ]);
    }
}
